### ISSUE TITLE
Faire la page de connexion

### ISSUE THREAD

**Issue by Jemery-Dev** [Jemery-Dev/MakiMalin#4]
On peut retrouver la maquette sur Figma, il suffit simplement de se connecter aux identifiants de la DB et de vérifier s'ils existent belle et bien. Sinon on affiche un message d'erreur classique en mode "hee hee ah identifant incorrect"
Potentiellement mettre un lien de redirection vers la page register en mode "Se créer un compte". On peut partir du principe que la page login est la page principale dès qu'on arrive sur le site, afin qu'on ne puisses pas entrer à moins d'être connecter
![image](https://github.com/Jemery-Dev/MakiMalin/assets/75862623/38391a4d-0d3c-426f-a7bf-deb83156a1c6)

**Comment by Axelrmd** [comment]
CSS terminé plus ou moins normalement
